### ISSUE TITLE
Integrate ads

### ISSUE THREAD

**Issue by krishdarling143** [rdkcentral/Lightning-SDK#110]
How To integrate Ads in Lightning is there any reference to integrate pre,mid,post roll ads

**Comment by michielvandergeest** [comment]
There exists a (hidden and experimental) Ads plugin in the Lightning-SDK. This plugin never has been officially published, since actually serving the Ads has many variables depending on the platform integration.

You can take a look at it though to get some inspiration how one could handle this: https://github.com/rdkcentral/Lightning-SDK/blob/master/src/Ads/index.js
