### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by vamshi4a3** [rdkcentral/Lightning-SDK#112]
can we play ads in media player.. if yes can u send any reference

**Comment by michielvandergeest** [comment]
There exists a (hidden and experimental) Ads plugin in the Lightning-SDK. This plugin never has been officially published, since actually serving the Ads has many variables depending on the platform integration.

You can take a look at it though to get some inspiration how one could handle this: https://github.com/rdkcentral/Lightning-SDK/blob/master/src/Ads/index.js
