### ISSUE TITLE
Z-index between video element and canvas element

### ISSUE THREAD

**Issue by fabiomssilva** [rdkcentral/Lightning-SDK#200]
Hi, 

I am trying to build a UI that involves UI elements like buttons, images, etc, and video using VideoPlayer plugin. 

There is any way to control the z-index of the <video> element created on the dom?
The <canvas> is created with a higher z-index and makes the video hidden behind the canvas. 

How can this be done ?
Looking forward for your answer. 

--Fabio

**Comment by michielvandergeest** [comment]
The video tag will always be placed _under_ the UI elements (on the canvas). So whenever you display video, you should make sure that you programatically set the alpha of (parts of) the overlaying UI to 0 in order to make the video visible.

This technique allows you to display something like a progress bar and play / pause buttons made in Lightning components on top of the video.

**Comment by fabiomssilva** [comment]
Hi, 

Thank you for the clarification. 
Since I took some time to find a way to find a solution I am sharing it here. 

The way I found to do it is to add a shader on the image. 

Example:

  static _template() {
    return {
      Background: {
        w: 1920,
        h: 1080,
        color: 0xfffbb03b,
        src: Utils.asset('images/background.png'),
        shader: {type: lng.shaders.Hole, x:200,y:200,h:200,w:250,radius:0}
      },
...

Thank you for your help.
