### ISSUE TITLE
VideoPlayer can't show 

### ISSUE THREAD

**Issue by CooperCao** [rdkcentral/Lightning-SDK#251]
![image](https://user-images.githubusercontent.com/14977519/124597831-869f9c80-de96-11eb-8d18-d1621f1f33fb.png)
![image](https://user-images.githubusercontent.com/14977519/124597859-8b645080-de96-11eb-841a-ec241de9675c.png)

if change the videoEl.style.zIndex = '1' to videoEl.style.zIndex = '2', the video on Edge can show, the RDK web still can't show.

**Comment by michielvandergeest** [comment]
By design the VideoPlayer is placed _below_ the canvas. This enables you to create an overlaying video player UI (i.e. progress bar, control buttons, etc.) in Lightning.

Whenever you're playing video in your App, you should manually make the background color of the main component (partially) transparent to make the video-tag visible

**Comment by CooperCao** [comment]
Ok , Thanks.
