### ISSUE TITLE
BootComponent: we get a warning for deprecating bootComponent but no documentation 

### ISSUE THREAD

**Issue by patrick007-glitch** [rdkcentral/Lightning-SDK#275]
Hi, 

We are implementing an app with a splash page on boot. When specifying bootComponent: SplashPage we get the warning for deprecation of this route and that it has a special route. 
![Screen Shot 2021-10-28 at 3 26 44 PM](https://user-images.githubusercontent.com/55208056/139322386-e7bd4a43-d3ec-4380-9a2e-ab3c965d7eea.png)
. 
However, upon following the link there is no documentation about this special router. 

![Screen Shot 2021-10-28 at 3 28 42 PM](https://user-images.githubusercontent.com/55208056/139322642-2bcba799-4cd8-4ae1-87a7-33c102f86876.png)

Another dev used the $ route but this no longer allows me to access queryStringParameters in the boot component as it becomes the splash page.

**Comment by erikhaandrikman** [comment]
Hi, 

We forgot to update the documentation for the new `bootComponent` route. 
Configuration now follows the rules of the other routes: 

```js
{
    path: '$',
    component: Boot
}
```

There was indeed an issue with request the correct querystring parameters, that we've fixed with this commit: https://github.com/rdkcentral/Lightning-SDK/commit/8a994765d9c6b1b13a9572bb481ea0b801810e74

I will update this ticket when it's available in master

**Comment by erikhaandrikman** [comment]
Fix is available in release `4.8.0`, we're working on updating the documentation
