### ISSUE TITLE
Does lightning support read write file operation?

### ISSUE THREAD

**Issue by Abhishk123** [rdkcentral/Lightning-SDK#293]
I have to do read write operation in file in lightning.is it possible to do in lightning.

**Comment by erikhaandrikman** [comment]
Since you've reached out to us via Slack i'm going to paste the answer here: 

_Lightning's responsibility is rendering graphics on screen via WebGL. It has no out of the box support for file I/O so that's a layer that you need to build yourself. I assume that you don't need to store that file locally right? So you can set-up (i.e) a REST web service that accepts POST request, and as it's body you send the JSON data you wish to store. Next thing, it's up to the Web service to store it into a JSON file:_
