### ISSUE TITLE
Router can't find the route by hash with query 

### ISSUE THREAD

**Issue by mikita-liaukovich-epam** [rdkcentral/Lightning-SDK#345]
## Pre-conditions:
Routes config: 
```js
export const routes = {
  root: PAGES.HOME,
  routes: [
    {
      path: "$",
      component: SplashScreen,
    },
    {
      path: PAGES.HOME,
      component: HomePage,
      widgets: [WIDGETS.MENU],
    },
    ...
}
```

URL: http://localhost:8082/?configUrl=http://localhost:8081/config.json#Home?action=showWiFi&wifiType=home

## Expected result
Router is parsing query parameters and navigates to the route #Home

## Actual result
Router is parsing query params (both in location.search and hash), but navigates to the route "*" (Not Found)

## Investigation
I guess I found a regression made 15 months ago, that breaks this flow in my case. @erikhaandrikman, could you please check this?

sdk/src/Router/index.js
![image](https://user-images.githubusercontent.com/43153354/187882924-46191048-914a-45be-ac3f-e4e211a695fd.png)

![image](https://user-images.githubusercontent.com/43153354/187882993-1c44b39d-f6b2-4027-92b0-c5cf997d5e64.png)

App is loading the splash screen ($) first, then Router is parsing the querystring and trying to navigate to the hashed route. But as we’re navigating it from Splash, then it’s not considered as a direct load, and there is no route by hash `#Home?action=showWifi…`, so function `start` is navigating to the NotFoundPage (*)

## Possible solution
My suggestion is to clean the hash from query parameters before checking the existence of the page by this hash (sdk/src/Router/index.js, in line 127). This fixes the issue in that case, but I can’t say that it’s 100% correct solution.

## Setup
SDK: 4.8.1
CLI: 2.8.1
Core: 2.6.0
Build: any (Metrological / standalone / dev standalone)
Browsers: Chrome 104, WPE (EOS)

**Comment by michielvandergeest** [comment]
@mikita-liaukovich-epam thanks for your (wonderfully detailed!) bug report and possible suggestion. One of our engineers will look into it.

**Comment by chiefcll** [comment]
Yes. The Hash first will prevent the browser from processing the queryparams. But the router should still parse it and provide the query information to the page.

**Comment by erikhaandrikman** [comment]
Hi, 
As @mauro1855 is already pointing out, the specification dictates that query string parameters should come before the hash (fragment). The issue you're facing is caused by this change: https://github.com/rdkcentral/Lightning-SDK/commit/44c73557e5668168f1664ecf7596502d8407647e that allowed all characters to be a part of the url.

Moving forward you can choose to take the following paths: 
- Build your url following the specification: `http://localhost:8081/config.json?action=showWiFi&wifiType=home#Home` the downside is that your page will refresh if you change the qs parameters.
- Turn your query string into dynamic parts of your url: 

```
{
    path: 'home/:action/wifiType',
    component: Home
}
```
And navigate to: 
`http://localhost:8081/config.json#Home/showWifi/home` 

This prevents the page from refreshing because it's now part of the hash:

- The last suggestion is a bit of an hack due to left over logic where we still parse query string parameters present in the hash we're routing to: https://github.com/rdkcentral/Lightning-SDK/blob/2b0d10e6d36ae9d855d8f0ac29e8eaccae807ebf/src/Router/utils/helpers.js#L124

If you update your configuration: 
```
{
    path: 'home/:qs',
    component: Home
}
```
And navigate to: 
`http://localhost:8081/config.json#Home/?action=showWifi&wifiType=home` 

the parameters will be available to the page via: 

```
set params(args){
    // args:  { action: 'showWifi', wifiType: 'home'}
}
```

**Comment by mikita-liaukovich-epam** [comment]
Hi @erikhaandrikman!

Thanks for your detailed answer, I'll try it this way

Btw, just as a temporary solution, I've made it work like this (maybe someone will encounter the same issue and it could be a solution):
```js
moveHashQueryToLocationSearch() {
    // get hash
    const hash = document.location.hash;

    // if it includes some query, then
    if (hash.indexOf("?") !== -1) {
      // read full url
      let url = document.location.href;
      // get existing search params
      const search = document.location.search;
      // get query from hash
      const hashQuery = hash.substring(hash.indexOf("?"));
      // remove found query from hash
      const cleanHash = hash.replace(hashQuery, "");
      // add 'hash query' to search params if there some
      const newSearch = search ? search + hashQuery.replace("?", "&") : hashQuery;

      // if query params exist, then
      if (search) {
        // remove query from hash
        url = url.replace(hashQuery, "");
        // update search params
        url = url.replace(search, newSearch);
      } else {
        // if there are no query params, then place hash query before the hash itself ("?query#hash)
        url = url.replace(hash, newSearch + cleanHash);
      }

      // if replaceState is available in browser, then replace it without reload, else just update the href with reload
      if (history.replaceState) {
        console.warn("history.replaceState is supported. No reload needed.");
        history.replaceState(null, null, url);
      }
      else {
        console.warn("history.replaceState not supported. Reloading page.");
        location.href = url;
      }
    }
  }
```

This method is called in `index.js` before the `Launch` function and Lightning Routing start. Maybe it's not the best solution, but at least it works as expected :)
